# Generated by Django 2.2.3 on 2019-07-16 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appforfirst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_project',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='appforfirst.Project'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='diary_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_project',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='appforfirst.Project'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appforfirst.Project'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
