# Generated by Django 2.2.6 on 2019-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforfirst', '0002_auto_20190716_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.CharField(max_length=20)),
                ('draw_number', models.CharField(max_length=20)),
                ('number_1', models.CharField(default='0', max_length=2)),
                ('number_2', models.CharField(default='0', max_length=2)),
                ('number_3', models.CharField(default='0', max_length=2)),
                ('number_4', models.CharField(default='0', max_length=2)),
                ('number_5', models.CharField(default='0', max_length=2)),
                ('number_6', models.CharField(default='0', max_length=2)),
            ],
        ),
    ]
