# Generated by Django 3.0.1 on 2019-12-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforfirst', '0003_lottonumbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_data_utworzenia',
            new_name='task_created',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('new', 'new'), ('in progres', 'in progres'), ('done', 'done'), ('postponed', 'postponed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_type',
            field=models.CharField(choices=[('meeting', 'meeting'), ('payment', 'payment'), ('todo', 'todo'), ('trip', 'trip'), ('other', 'other'), ('professional', 'professional')], max_length=50),
        ),
    ]
